# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image with a version >= 18
FROM node:18-bullseye-slim AS builder

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory inside the Docker image
WORKDIR /app

# Copy the project files into the Docker image
COPY . .

# Install project dependencies
RUN pnpm install

# Build the project
RUN pnpm build

# Install Playwright browsers
RUN pnpm exec playwright install chromium

# Final image for running
FROM node:18-bullseye-slim

WORKDIR /app

# Copy the built files and dependencies from the builder
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Set the environment variable for Playwright to skip downloading browsers again
ENV PLAYWRIGHT_BROWSERS_PATH=/app/node_modules/.cache/ms-playwright

# Expose any ports the app might use (not specified in README)
# EXPOSE 3000 

# Run the server
ENTRYPOINT ["node", "dist/index.js"]
